### ISSUE TITLE
0.1 Roadmap

### ISSUE THREAD

**Issue by oyeanuj** [FineUploader/react-fine-uploader#32]
Hi @rnicholus! This looks a great project and I needed something similar, so wanted to get a sense if this might be the right fit. 

On the README, you mentioned that the project is very unstable and the design is in flux and that there won't be a published version until 0.1. So, I was hoping to better understand what the scope or roadmap for 0.1 might look like? What are the things that you might be looking at, what is the state of the current library for usage and if there was any rough timeframe on your end?

Thank you for open sourcing this!

**Comment by rnicholus** [comment]
Hi! 

>what the scope or roadmap for 0.1 might look like

You can find the progress for 0.1.0 in [the associated issue milestone](https://github.com/FineUploader/react-fine-uploader/milestone/1). As you can see, all planned cases other than the `<Gallery />` component, which is in-progress, are done. The `<Gallery />` component is meant to mirror the gallery template in Fine Uploader UI, which you can see demonstrated on the demo page in various places at http://fineuploader.com/demos (for example, in the first demo on that page). Once the `<Gallery />` component is finished, it will be amazingly easy to get integrate Fine Uploader into your React app, and use all of the powerful features bundled with the library in a pre-set but easily configurable UI. 

> what is the state of the current library for usage

React Fine Uploader is a React wrapper for the Fine Uploader library (which itself is library and framework agnostic). [Fine Uploader](https://github.com/FineUploader/fine-uploader) is popular and very widely used, but React Fine Uploader is still in early development. 

Since I haven't published the initial version yet, it is not yet used by anyone (at least that I know of). However, I expect to need React Fine Uploader in some internal projects being developed by my employer, [Widen](http://www.widen.com/). This is what prompted the initial effort. Once 0.1.0 is out, I expect to list React Fine Uploader on the front page of http://fineuploader.com, which I expect will draw a lot of traffic to the project. Please do spread the word though, as I'd like to get more eyes on the project as early as possible.

> any rough timeframe on your end?

Yes, I expect to have v0.1.0 published within the next few weeks, possibly earlier. Please note that, until we hit 1.0.0, breaking changes may occur at any time as I receive input from users and make realizations based on observations "in the field". 1.0.0 will be published once I'm satisfied that the API and design are solid enough to resist the need to introduce breaking changes in the near future. You can follow [the GitHub project that includes all cases that must be completed before the first stable release](https://github.com/FineUploader/react-fine-uploader/projects/1) (such as 1.0.0) for updates on that longer-term goal. Cases may be added, removed, or changed over time.

Any questions or requests for features/clarification are welcome. Help in the form of design work, development work (PRs), and feedback is also _very_ welcome. I am only one man!

**Comment by rnicholus** [comment]
Since I haven't heard anything further, I assume I've addressed your question. If not, please let me know.

**Comment by oyeanuj** [comment]
Hey @rnicholus! Sorry, I missed writing back! I noticed a lot of progress has been made since, that is really good to see - congrats and thank you for all of your effort, doing it all alone!

Also, it is very helpful to see the 1.0 project seeing all the issues remaining. I am curious if you had a mental timeline for when you see that being wrapped up or if you think it is fairly usable already? No rush or pressure, just curious so that I can plan accordingly :)

Thank you again!

**Comment by rnicholus** [comment]
>congrats and thank you for all of your effort, doing it all alone

Thanks! FOSS development can be a surprisingly lonely and harsh environment, so I always appreciate hearing this.

>I am curious if you had a mental timeline for when you see that being wrapped up or if you think it is fairly usable already

I see React Fine Uploader as being very much usable at the moment. I should probably go through the "First Stable Release" project to include only the most necessary features and adjustments. I'm also waiting for a little more feedback from users before I feel comfortable making this a 1.0.0 library. At the moment, the "major" features are already completed, including S3 and Azure support. If there is something important missing or if you see a feature that you require, please do comment on that issue or create a new one so we can discuss. Otherwise, do let me know if you have any further questions.

**Comment by oyeanuj** [comment]
> FOSS development can be a surprisingly lonely and harsh environment,
Totally hear you. I hope a lot more of us appreciate than the comments might indicate, so I'm just representing the silent majority's sentiments :)

In terms of feedback, I feel like all the important pieces seem to be there. The only thing which I was looking to find but couldn't were some demo links or examples showcasing the different way of using `React-Fine-Uploader`. I have always found that to be the most helpful when understanding how a library works since it also shows the conventions from the author themselves.

Personally, I was wondering (and this could be an example-case), if it is possible to use it in conjunction with my own UI for dragging and dropping files. So, without needing the styling or the `Gallery` component, etc, if I put in lets's say,  the `DropZone`, `FileInput`, and `ProgressBar` component - would I be able to do that? Or do they all play together?

My use-case is that I already have an album page and I'd like to just be able to drop some of the components into my page and have them power the file upload while giving me back the information like progress, etc that I can style and show in my own way.

Thoughts?

**Comment by rnicholus** [comment]
Yes, you can absolutely make direct and exclusive use the lower level components (such as `<DropZone>` and `<FileInput>`). React Fine Uploader was designed to provide a rich turn-key UI built on top of small and focused components.  I put a great deal of time into the `README..md` file, which heavily documents all components and provides code examples for each. 

The`<Gallery>` component includes a code example with screenshots in the readme as well, and they component itself acts as a function demonstration for the lower level components that it is built on top of. 

Are there other specific examples you would like to see as well?

**Comment by oyeanuj** [comment]
Got it, that context is helpful - I'll play with it more and let you know how it goes.

> Are there other specific examples you would like to see as well?
The only thing I can think of is for the 1.0 stable release is to provide somerunning code - either on GH pages or examples one can clone and play with.

For now and for my case, I think the Readme works just as well :)

**Comment by rnicholus** [comment]
v1.0 is about to be released. Just pushed on 1.0.0-rc1 today.
